### ISSUE TITLE
Missing part of path to templates.json

### ISSUE THREAD

**Issue by MatthewAWood** [stringandstickytape/MaxsAiStudio#2] opened 2024-08-14 20:27 UTC
On first run the software looks for "Templates/templates.json" but the Templates folder must be manually created or you get an exception

**Comment by stringandstickytape** [comment] 2024-08-25 23:15
TY, this will be fixed in the next version.  Caused by the TemplateManager injected dependency being constructed before the Form constructor runs...

**Closed** 2024-08-25 23:14 UTC
